id = "pop-theme"
name = "Pop Theme"
version = "0.1.0"
schema_version = 1
authors = ["Anatoly Tsyplenkov <sharp.couch9400@fastmail.com>"]
description = "A port of the Pop!_OS design language for Zed, inspired by System76."
repository = "https://github.com/atsyplenkov/zed-pop-theme"
